spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.93.0.240:3306/hrdb
    username: hrdb
    password: 123456

  servlet:
    multipart:
      max-file-size: 1MB
server:
  port: 80
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.kgc.sun.hr.pojo
#  延迟加载
  configuration:
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
    #全部映射
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl